name: CI

on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup deployment
        run: |
          cd ../../ mvn clean
          cd ../../ mvn instll
          cd ../../ mvn compile
          git add target -f
          git commit -m "build spring project"
          git push